# Generated by Django 4.1.7 on 2023-11-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=255, null=True, verbose_name='Renseigner la catégorie du produit')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('description', models.TextField(null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('quantite', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.categorieproduit')),
            ],
        ),
    ]
