# Generated by Django 4.1.7 on 2023-11-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0002_categorieproduit_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='nom',
            new_name='titre',
        ),
    ]
