# Generated by Django 4.1.7 on 2023-11-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0003_rename_nom_produit_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.FileField(null=True, upload_to='produits/'),
        ),
    ]
