# Generated by Django 4.2.7 on 2023-11-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0006_alter_produit_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='titre',
            new_name='designation',
        ),
    ]
