# Generated by Django 4.2.7 on 2023-11-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0007_rename_titre_produit_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='produit',
            name='ancien_prix',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
