# Generated by Django 4.2.7 on 2023-11-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0008_rename_image_produit_image1_produit_ancien_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='ancien_prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
