# Generated by Django 4.2.7 on 2023-11-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0009_alter_produit_ancien_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image1',
            field=models.ImageField(null=True, upload_to='produits/'),
        ),
    ]
