# Generated by Django 4.2.7 on 2023-11-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0011_rename_date_produit_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='mini_description',
            field=models.TextField(null=True, verbose_name='Brève description'),
        ),
    ]
