# Generated by Django 4.2.7 on 2023-12-05 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0012_produit_image3_produit_image4_produit_image5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=100, null=True)),
                ('code_pays', models.CharField(max_length=15, null=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Droits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_droit', models.CharField(max_length=255)),
                ('archive', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DroitsProfils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecriture', models.BooleanField(default=False, null=True)),
                ('lecture', models.BooleanField(default=False, null=True)),
                ('modification', models.BooleanField(default=False, null=True)),
                ('suppression', models.BooleanField(default=False, null=True)),
                ('droit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.droits')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_groupe', models.CharField(help_text='Le nom du groupe permet de différencier les groupes, ex. Groupe 1', max_length=255, null=True)),
                ('manageur_du_groupe', models.CharField(help_text='Celui pour qui le groupe se cré et contiendra tous ses filleuls', max_length=255)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_niveau', models.CharField(max_length=255, null=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_poste', models.CharField(max_length=255, null=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='annee_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='user',
            name='dix_milles',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='don_bam',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='don_mand',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='don_maya',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='don_zou',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gam',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nb_pers_amene',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nom_du_parent',
            field=models.ForeignKey(blank=True, help_text="Indiquez le parent qui l'adhère. S'il est le premier membre de son groupe, laissez vide", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Parrain'),
        ),
        migrations.AddField(
            model_name='user',
            name='pied_droit',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pied_gauche',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='point_a_affecter',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='point_fictive_col',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='point_fictive_inv',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='point_fictive_manag',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], help_text='Le sexe servira pour les statistiques', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stock_point',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Profils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('archive', models.BooleanField(default=False, null=True)),
                ('droits', models.ManyToManyField(through='affiliation.DroitsProfils', to='affiliation.droits')),
            ],
        ),
        migrations.CreateModel(
            name='Palier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_palier', models.CharField(max_length=255, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.niveau')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='droitsprofils',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.profils'),
        ),
        migrations.AddField(
            model_name='user',
            name='groupe',
            field=models.ForeignKey(help_text="Le groupe permettra de voir l'ensemble de ses membres", null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.groupe', verbose_name="Nom de l'équipe"),
        ),
        migrations.AddField(
            model_name='user',
            name='palier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.palier'),
        ),
        migrations.AddField(
            model_name='user',
            name='pays_de_residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.codepays'),
        ),
        migrations.AddField(
            model_name='user',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.poste'),
        ),
        migrations.AddField(
            model_name='user',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.profils'),
        ),
    ]
