# Generated by Django 4.2.7 on 2023-12-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0013_codepays_droits_droitsprofils_groupe_niveau_poste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image2',
            field=models.ImageField(null=True, upload_to='produits/'),
        ),
    ]
