# Generated by Django 4.2.7 on 2023-12-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0014_alter_produit_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adresse',
        ),
    ]
