# Generated by Django 4.2.7 on 2023-12-06 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0015_remove_user_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pays_de_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.codepays'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
