# Generated by Django 4.2.7 on 2023-12-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0017_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publie',
            field=models.BooleanField(default=False, verbose_name='Mise en ligne'),
        ),
    ]
