# Generated by Django 4.2.7 on 2023-12-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0018_blog_publie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
    ]
