# Generated by Django 4.2.7 on 2023-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0019_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
