# Generated by Django 4.2.7 on 2023-12-12 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0020_alter_newsletter_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='categorieblog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.categorieblog'),
        ),
    ]
